/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.pr.senac.ads.peixaria.view;

import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import br.pr.senac.ads.peixaria.controller.PeixariaController;
import br.pr.senac.ads.peixaria.dao.VendaDAO;
import br.pr.senac.ads.peixaria.model.Venda;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author rsdav
 */
public class PeixariaHome extends javax.swing.JDialog {

    /**
     * Creates new form Peixaria
     */
    public PeixariaHome(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarBanco();
    }

    double caixa;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrecoUnitario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerQuantidade = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTotalProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCaixa = new javax.swing.JTextField();
        jButtonVender = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();
        jButtonAlterar = new javax.swing.JButton();
        jButtonAlterarFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3), "Peixaria Home", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Selecione o produto:");

        jComboBoxProduto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum...", "Tilápia", "Tambaqui", "Pacu", "Dourado", "Camarão" }));
        jComboBoxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Preço Unitário:");

        jTextFieldPrecoUnitario.setEditable(false);
        jTextFieldPrecoUnitario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Quantidade:");

        jSpinnerQuantidade.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jSpinnerQuantidade.setModel(new SpinnerNumberModel(0,0,100,1));
        jSpinnerQuantidade.setToolTipText("Informe a quantidade em KG");
        jSpinnerQuantidade.setNextFocusableComponent(jTextFieldTotalProduto);
        jSpinnerQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQuantidadeStateChanged(evt);
            }
        });
        jSpinnerQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinnerQuantidadeKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Total do Produto:");

        jTextFieldTotalProduto.setEditable(false);
        jTextFieldTotalProduto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("X");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("=");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Caixa:");

        jTextFieldCaixa.setEditable(false);
        jTextFieldCaixa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextFieldCaixa.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldCaixa.setText("R$ 0.0");

        jButtonVender.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonVender.setForeground(new java.awt.Color(153, 0, 0));
        jButtonVender.setText("Vender");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });

        jTableLista.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Preço Unitário", "Quantidade", "Preço Total", "Caixa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLista);

        jButtonAlterar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(0, 0, 204));
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonAlterarFechar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonAlterarFechar.setForeground(new java.awt.Color(153, 0, 0));
        jButtonAlterarFechar.setText("Fechar");
        jButtonAlterarFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBoxProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldPrecoUnitario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSpinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTotalProduto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAlterarFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldTotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(jTextFieldCaixa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAlterarFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutoActionPerformed
        // TODO add your handling code here:

        String produto = jComboBoxProduto.getSelectedItem().toString();

        switch (produto) {
            case "Tilápia":
                jTextFieldPrecoUnitario.setText("R$ 39.90");
                break;
            case "Tambaqui":
                jTextFieldPrecoUnitario.setText("R$ 49.90");
                break;
            case "Pacu":
                jTextFieldPrecoUnitario.setText("R$ 49.90");
                break;
            case "Dourado":
                jTextFieldPrecoUnitario.setText("R$ 89.90");
                break;
            case "Camarão":
                jTextFieldPrecoUnitario.setText("R$ 99.90");
                break;
            default:
                jTextFieldPrecoUnitario.setText("");
                break;
        }
    }//GEN-LAST:event_jComboBoxProdutoActionPerformed

    private void jSpinnerQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQuantidadeStateChanged

        try {
            int quantidade = Integer.parseInt(jSpinnerQuantidade.getValue().toString());

            if (quantidade != 0) {
                double precoUnitario = Double.parseDouble(jTextFieldPrecoUnitario.getText()
                        .replace("R$ ", "")
                        .replace(",", "."));
                double totalProduto = quantidade * precoUnitario;
                jTextFieldTotalProduto.setText(String.valueOf(totalProduto));
            } else {
                limparCampos();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto1!!");
            e.printStackTrace();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto2!!");
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um produto3!!");
            e.printStackTrace();
        }


    }//GEN-LAST:event_jSpinnerQuantidadeStateChanged

    private void jSpinnerQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerQuantidadeKeyPressed

    }//GEN-LAST:event_jSpinnerQuantidadeKeyPressed

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed
        // TODO add your handling code here:

        if (!jComboBoxProduto.getSelectedItem().equals("Nenhum...")) {
            double totalProduto = Double.parseDouble(jTextFieldTotalProduto.getText().replace("R$ ", ""));
            caixa = Double.parseDouble(jTextFieldCaixa.getText().replace("R$ ", ""));

            caixa = caixa + totalProduto;

            jTextFieldCaixa.setText(String.valueOf(caixa));
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto!!");
        }
        
        PeixariaController controlarPeixaria = new PeixariaController();
        
        controlarPeixaria.setProduto(jComboBoxProduto.getSelectedItem().toString());
        controlarPeixaria.setPrecoUnitario(jTextFieldPrecoUnitario.getText().replace("R$ ", ""));
        controlarPeixaria.setQuantidade(jSpinnerQuantidade.getValue().toString());
        controlarPeixaria.setPrecoTotal(jTextFieldTotalProduto.getText());
        controlarPeixaria.setCaixa(jTextFieldCaixa.getText().replace("R$ ", ""));
        
        try {
            controlarPeixaria.salvar(
                    controlarPeixaria.getProduto(),
                    controlarPeixaria.getPrecoUnitario(),
                    controlarPeixaria.getQuantidade(),
                    controlarPeixaria.getPrecoTotal(),
                    controlarPeixaria.getCaixa());
                    JOptionPane.showMessageDialog(this, "Venda salva com sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Não foi possível salvar a venda!" + e.getLocalizedMessage());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Erro no Código fonte!" + e.getLocalizedMessage());
        }
        
        limparCampos();
        listarBanco();
        jSpinnerQuantidade.setValue(0);
    }//GEN-LAST:event_jButtonVenderActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        dispose();
        PeixariaPesquisar dialog = new PeixariaPesquisar(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonAlterarFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonAlterarFecharActionPerformed

    public void listarBanco() {
        
        try {
            VendaDAO objVenda = new VendaDAO();
            DefaultTableModel model = (DefaultTableModel) jTableLista.getModel();
            model.setRowCount(0);
            
            ArrayList<Venda> lista = objVenda.listarTodos();
            
            for(int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[] {
                    lista.get(i).getCodigo(),
                    lista.get(i).getProduto(),
                    lista.get(i).getPrecoUnitario(),
                    lista.get(i).getQuantidade(),
                    lista.get(i).getPrecoTotal(),
                    lista.get(i).getCaixa()
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no ListarCampos!");
        }
        
    }
    
    public void limparCampos() {
        jComboBoxProduto.setSelectedIndex(0);
        jTextFieldPrecoUnitario.setText("");
        jTextFieldTotalProduto.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAlterarFechar;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerQuantidade;
    private javax.swing.JTable jTableLista;
    private javax.swing.JTextField jTextFieldCaixa;
    private javax.swing.JTextField jTextFieldPrecoUnitario;
    private javax.swing.JTextField jTextFieldTotalProduto;
    // End of variables declaration//GEN-END:variables
}
